export const DEFAULT_TARGET_LANGUAGE_CODE = "vi-VN";

const supportedTargetLanguages = [
  { code: "af-ZA", name: "Cộng hòa Nam Phi" },
  { code: "bg-BG", name: "Cộng hòa Bulgaria" },
  { code: "lv-LV", name: "Cộng hòa Latvia" },
  { code: "sr-RS", name: "Cộng hòa Serbia" },
  { code: "sk-SK", name: "Cộng hòa Slovakia" },
  { code: "cs-CZ", name: "Cộng hòa Séc" },
  { code: "da-DK", name: "Đan Mạch" },
  { code: "de-DE", name: "Đức" },
  { code: "nl-NL", name: "Hà Lan" },
  { code: "nl-BE", name: "Hà Lan (Bỉ)" },
  { code: "yue-HK", name: "Hồng Kông" },
  { code: "hu-HU", name: "Hungary" },
  { code: "el-GR", name: "Hy Lạp" },
  { code: "is-IS", name: "Iceland" },
  { code: "id-ID", name: "Indonesia" },
  { code: "kn-IN", name: "Ấn Độ (Kannada)" },
  { code: "gu-IN", name: "Ấn Độ (Gujarati)" },
  { code: "hi-IN", name: "Ấn Độ (Hindi)" },
  { code: "ml-IN", name: "Ấn Độ (Malayalam)" },
  { code: "pa-IN", name: "Ấn Độ (Punjabi)" },
  { code: "ta-IN", name: "Ấn Độ (Tamil)" },
  { code: "te-IN", name: "Ấn Độ (Telugu)" },
  { code: "it-IT", name: "Ý" },
  { code: "ja-JP", name: "Nhật bản" },
  { code: "ko-KR", name: "Hàn Quốc" },
  { code: "ms-MY", name: "Malaysia" },
  { code: "nb-NO", name: "Na-Uy" },
  { code: "ru-RU", name: "Nga" },
  { code: "fr-FR", name: "Pháp" },
  { code: "fr-CA", name: "Pháp (Canada)" },
  { code: "fi-FI", name: "Phần Lan" },
  { code: "fil-PH", name: "Philippines" },
  { code: "pl-PL", name: "Ba Lan" },
  { code: "pt-PT", name: "Bồ Đào Nha" },
  { code: "pt-BR", name: "Bồ Đào Nha (Brazil)" },
  { code: "ar-XA", name: "Ả Rập Xê Út" },
  { code: "ro-RO", name: "Rô Man" },
  { code: "sv-SE", name: "Thụy Điển" },
  { code: "th-TH", name: "Thái Lan" },
  { code: "tr-TR", name: "Thổ Nhĩ Kỳ" },
  { code: "bn-IN", name: "Tây Bengal" },
  { code: "es-ES", name: "Tây Ban Nha" },
  { code: "ca-ES", name: "Tây Ban Nha (Catalan)" },
  { code: "es-US", name: "Tây Ban Nha (Mỹ)" },
  { code: "en-AU", name: "Tiếng Anh (Úc)" },
  { code: "en-GB", name: "Tiếng Anh (Anh)" },
  { code: "en-IN", name: "Tiếng Anh (Ấn)" },
  { code: "en-US", name: "Tiếng Anh (Mỹ)" },
  { code: "en-NZ", name: "Tiếng Anh New Zealand" },
  { code: "en-ZA", name: "Tiếng Anh Nam Phi" },
  { code: "cmn-CN", name: "Trung Quốc (Phổn thể)" },
  { code: "uk-UA", name: "Ukraina" },
  { code: "vi-VN", name: "Việt Nam" },
] as const;

export const targetLanguages = [...supportedTargetLanguages].sort((first, second) =>
  first.name.localeCompare(second.name, "vi", { sensitivity: "base" }),
);
